go_library(
    name = "domain",
    srcs = glob(["*.go"], exclude = ["*_test.go"]),
    package_name = "github.com/abilisoft/usbip-go/pkg/domain",
    visibility = ["PUBLIC"],
)

go_test(
    name = "domain_test",
    srcs = glob(["*_test.go"]),
    target_under_test = ":domain",
)
