// SPDX-FileCopyrightText: 2026 AbiliSoft
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/tools/gen_usb_ids.go from usb.ids; DO NOT EDIT.
//
// This file is a hand-maintained seed of the USB class-code table. It
// is committed in the generated-code form so that the future
// `go generate ./...` replacement can overwrite it wholesale without
// churning review.

package domain

// USB base class codes (bDeviceClass / bInterfaceClass). Source:
// https://www.usb.org/defined-class-codes and
// https://www.linux-usb.org/usb.ids (committed subset).
const (
	usbClassUseInterface   USBClass = 0x00
	usbClassAudio          USBClass = 0x01
	usbClassComms          USBClass = 0x02
	usbClassHID            USBClass = 0x03
	usbClassPhysical       USBClass = 0x05
	usbClassImage          USBClass = 0x06
	usbClassPrinter        USBClass = 0x07
	usbClassMassStorage    USBClass = 0x08
	usbClassHub            USBClass = 0x09
	usbClassCDCData        USBClass = 0x0A
	usbClassSmartCard      USBClass = 0x0B
	usbClassContentSec     USBClass = 0x0D
	usbClassVideo          USBClass = 0x0E
	usbClassHealthcare     USBClass = 0x0F
	usbClassAudioVideo     USBClass = 0x10
	usbClassBillboard      USBClass = 0x11
	usbClassTypeCBridge    USBClass = 0x12
	usbClassDiagnostic     USBClass = 0xDC
	usbClassWireless       USBClass = 0xE0
	usbClassMiscellaneous  USBClass = 0xEF
	usbClassApplicationSpc USBClass = 0xFE
	usbClassVendorSpecific USBClass = 0xFF
)

// usbClassName returns the canonical lowercase-kebab name for a USB class
// code, or ("", false) if the class is not known to the committed
// usb.ids subset.
//
// Implementation note: the Go compiler lowers a dense constant-case
// switch into a jump table, giving O(1) lookup with zero allocation.
// This satisfies gochecknoglobals (no package-level map) AND avoids the
// per-call slice/map construction that a function-returning-literal
// pattern would require. Generated replacements (internal/tools/gen_usb_ids.go)
// emit the same switch shape, so the migration is mechanical.
func usbClassName(c USBClass) (string, bool) {
	switch c {
	case usbClassUseInterface:
		return "use-interface-descriptor", true
	case usbClassAudio:
		return "audio", true
	case usbClassComms:
		return "communications", true
	case usbClassHID:
		return "hid", true
	case usbClassPhysical:
		return "physical", true
	case usbClassImage:
		return "image", true
	case usbClassPrinter:
		return "printer", true
	case usbClassMassStorage:
		return "mass-storage", true
	case usbClassHub:
		return "hub", true
	case usbClassCDCData:
		return "cdc-data", true
	case usbClassSmartCard:
		return "smart-card", true
	case usbClassContentSec:
		return "content-security", true
	case usbClassVideo:
		return "video", true
	case usbClassHealthcare:
		return "personal-healthcare", true
	case usbClassAudioVideo:
		return "audio-video", true
	case usbClassBillboard:
		return "billboard", true
	case usbClassTypeCBridge:
		return "usb-type-c-bridge", true
	case usbClassDiagnostic:
		return "diagnostic", true
	case usbClassWireless:
		return "wireless", true
	case usbClassMiscellaneous:
		return "miscellaneous", true
	case usbClassApplicationSpc:
		return "application-specific", true
	case usbClassVendorSpecific:
		return "vendor-specific", true
	default:
		return "", false
	}
}
