package domain

// USB base class codes (bDeviceClass / bInterfaceClass). Source:
// https://www.usb.org/defined-class-codes and
// https://www.linux-usb.org/usb.ids (committed subset). The full mapping
// is generated by `go generate ./pkg/domain/...` via
// internal/tools/gen_usb_ids.go (follow-up task); these constants are
// the minimum-viable committed baseline for v1.
const (
	usbClassUseInterface   USBClass = 0x00
	usbClassAudio          USBClass = 0x01
	usbClassComms          USBClass = 0x02
	usbClassHID            USBClass = 0x03
	usbClassPhysical       USBClass = 0x05
	usbClassImage          USBClass = 0x06
	usbClassPrinter        USBClass = 0x07
	usbClassMassStorage    USBClass = 0x08
	usbClassHub            USBClass = 0x09
	usbClassCDCData        USBClass = 0x0A
	usbClassSmartCard      USBClass = 0x0B
	usbClassContentSec     USBClass = 0x0D
	usbClassVideo          USBClass = 0x0E
	usbClassHealthcare     USBClass = 0x0F
	usbClassAudioVideo     USBClass = 0x10
	usbClassBillboard      USBClass = 0x11
	usbClassTypeCBridge    USBClass = 0x12
	usbClassDiagnostic     USBClass = 0xDC
	usbClassWireless       USBClass = 0xE0
	usbClassMiscellaneous  USBClass = 0xEF
	usbClassApplicationSpc USBClass = 0xFE
	usbClassVendorSpecific USBClass = 0xFF
)

// usbClassEntry pairs a class code with its canonical name for lookup.
type usbClassEntry struct {
	code USBClass
	name string
}

// usbClassTable is the committed usb.ids subset. Kept as a local slice
// (not a package-level global) to satisfy gochecknoglobals; the closure
// is allocated lazily via usbClassName.
func usbClassTable() []usbClassEntry {
	return []usbClassEntry{
		{usbClassUseInterface, "use-interface-descriptor"},
		{usbClassAudio, "audio"},
		{usbClassComms, "communications"},
		{usbClassHID, "hid"},
		{usbClassPhysical, "physical"},
		{usbClassImage, "image"},
		{usbClassPrinter, "printer"},
		{usbClassMassStorage, "mass-storage"},
		{usbClassHub, "hub"},
		{usbClassCDCData, "cdc-data"},
		{usbClassSmartCard, "smart-card"},
		{usbClassContentSec, "content-security"},
		{usbClassVideo, "video"},
		{usbClassHealthcare, "personal-healthcare"},
		{usbClassAudioVideo, "audio-video"},
		{usbClassBillboard, "billboard"},
		{usbClassTypeCBridge, "usb-type-c-bridge"},
		{usbClassDiagnostic, "diagnostic"},
		{usbClassWireless, "wireless"},
		{usbClassMiscellaneous, "miscellaneous"},
		{usbClassApplicationSpc, "application-specific"},
		{usbClassVendorSpecific, "vendor-specific"},
	}
}

// usbClassName returns the canonical lowercase-kebab name for a USB class
// code, or ("", false) if the class is not known to the committed
// usb.ids subset.
func usbClassName(c USBClass) (string, bool) {
	for _, e := range usbClassTable() {
		if e.code == c {
			return e.name, true
		}
	}

	return "", false
}
