// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app_test

import (
	"github.com/abilisoft/usbip-go/internal/adapter/wire"
	"github.com/abilisoft/usbip-go/internal/app"
	"github.com/abilisoft/usbip-go/pkg/domain"
	"io"
	"sync"
)

// Ensure, that ProtocolCodecMock does implement app.ProtocolCodec.
// If this is not the case, regenerate this file with moq.
var _ app.ProtocolCodec = &ProtocolCodecMock{}

// ProtocolCodecMock is a mock implementation of app.ProtocolCodec.
//
//	func TestSomethingThatUsesProtocolCodec(t *testing.T) {
//
//		// make and configure a mocked app.ProtocolCodec
//		mockedProtocolCodec := &ProtocolCodecMock{
//			DecodeHeaderFunc: func(r io.Reader) (uint16, wire.OpCode, uint32, error) {
//				panic("mock out the DecodeHeader method")
//			},
//			DecodeOpRepDevlistFunc: func(r io.Reader) ([]domain.Device, error) {
//				panic("mock out the DecodeOpRepDevlist method")
//			},
//			DecodeOpRepImportFunc: func(r io.Reader) (domain.Device, error) {
//				panic("mock out the DecodeOpRepImport method")
//			},
//			DecodeOpReqImportFunc: func(r io.Reader) (domain.BusID, error) {
//				panic("mock out the DecodeOpReqImport method")
//			},
//			EncodeOpRepDevlistFunc: func(w io.Writer, devs []domain.Device) error {
//				panic("mock out the EncodeOpRepDevlist method")
//			},
//			EncodeOpRepImportFunc: func(w io.Writer, d domain.Device) error {
//				panic("mock out the EncodeOpRepImport method")
//			},
//			EncodeOpReqDevlistFunc: func() []byte {
//				panic("mock out the EncodeOpReqDevlist method")
//			},
//			EncodeOpReqImportFunc: func(w io.Writer, busID domain.BusID) error {
//				panic("mock out the EncodeOpReqImport method")
//			},
//		}
//
//		// use mockedProtocolCodec in code that requires app.ProtocolCodec
//		// and then make assertions.
//
//	}
type ProtocolCodecMock struct {
	// DecodeHeaderFunc mocks the DecodeHeader method.
	DecodeHeaderFunc func(r io.Reader) (uint16, wire.OpCode, uint32, error)

	// DecodeOpRepDevlistFunc mocks the DecodeOpRepDevlist method.
	DecodeOpRepDevlistFunc func(r io.Reader) ([]domain.Device, error)

	// DecodeOpRepImportFunc mocks the DecodeOpRepImport method.
	DecodeOpRepImportFunc func(r io.Reader) (domain.Device, error)

	// DecodeOpReqImportFunc mocks the DecodeOpReqImport method.
	DecodeOpReqImportFunc func(r io.Reader) (domain.BusID, error)

	// EncodeOpRepDevlistFunc mocks the EncodeOpRepDevlist method.
	EncodeOpRepDevlistFunc func(w io.Writer, devs []domain.Device) error

	// EncodeOpRepImportFunc mocks the EncodeOpRepImport method.
	EncodeOpRepImportFunc func(w io.Writer, d domain.Device) error

	// EncodeOpReqDevlistFunc mocks the EncodeOpReqDevlist method.
	EncodeOpReqDevlistFunc func() []byte

	// EncodeOpReqImportFunc mocks the EncodeOpReqImport method.
	EncodeOpReqImportFunc func(w io.Writer, busID domain.BusID) error

	// calls tracks calls to the methods.
	calls struct {
		// DecodeHeader holds details about calls to the DecodeHeader method.
		DecodeHeader []struct {
			// R is the r argument value.
			R io.Reader
		}
		// DecodeOpRepDevlist holds details about calls to the DecodeOpRepDevlist method.
		DecodeOpRepDevlist []struct {
			// R is the r argument value.
			R io.Reader
		}
		// DecodeOpRepImport holds details about calls to the DecodeOpRepImport method.
		DecodeOpRepImport []struct {
			// R is the r argument value.
			R io.Reader
		}
		// DecodeOpReqImport holds details about calls to the DecodeOpReqImport method.
		DecodeOpReqImport []struct {
			// R is the r argument value.
			R io.Reader
		}
		// EncodeOpRepDevlist holds details about calls to the EncodeOpRepDevlist method.
		EncodeOpRepDevlist []struct {
			// W is the w argument value.
			W io.Writer
			// Devs is the devs argument value.
			Devs []domain.Device
		}
		// EncodeOpRepImport holds details about calls to the EncodeOpRepImport method.
		EncodeOpRepImport []struct {
			// W is the w argument value.
			W io.Writer
			// D is the d argument value.
			D domain.Device
		}
		// EncodeOpReqDevlist holds details about calls to the EncodeOpReqDevlist method.
		EncodeOpReqDevlist []struct {
		}
		// EncodeOpReqImport holds details about calls to the EncodeOpReqImport method.
		EncodeOpReqImport []struct {
			// W is the w argument value.
			W io.Writer
			// BusID is the busID argument value.
			BusID domain.BusID
		}
	}
	lockDecodeHeader       sync.RWMutex
	lockDecodeOpRepDevlist sync.RWMutex
	lockDecodeOpRepImport  sync.RWMutex
	lockDecodeOpReqImport  sync.RWMutex
	lockEncodeOpRepDevlist sync.RWMutex
	lockEncodeOpRepImport  sync.RWMutex
	lockEncodeOpReqDevlist sync.RWMutex
	lockEncodeOpReqImport  sync.RWMutex
}

// DecodeHeader calls DecodeHeaderFunc.
func (mock *ProtocolCodecMock) DecodeHeader(r io.Reader) (uint16, wire.OpCode, uint32, error) {
	if mock.DecodeHeaderFunc == nil {
		panic("ProtocolCodecMock.DecodeHeaderFunc: method is nil but ProtocolCodec.DecodeHeader was just called")
	}
	callInfo := struct {
		R io.Reader
	}{
		R: r,
	}
	mock.lockDecodeHeader.Lock()
	mock.calls.DecodeHeader = append(mock.calls.DecodeHeader, callInfo)
	mock.lockDecodeHeader.Unlock()
	return mock.DecodeHeaderFunc(r)
}

// DecodeHeaderCalls gets all the calls that were made to DecodeHeader.
// Check the length with:
//
//	len(mockedProtocolCodec.DecodeHeaderCalls())
func (mock *ProtocolCodecMock) DecodeHeaderCalls() []struct {
	R io.Reader
} {
	var calls []struct {
		R io.Reader
	}
	mock.lockDecodeHeader.RLock()
	calls = mock.calls.DecodeHeader
	mock.lockDecodeHeader.RUnlock()
	return calls
}

// DecodeOpRepDevlist calls DecodeOpRepDevlistFunc.
func (mock *ProtocolCodecMock) DecodeOpRepDevlist(r io.Reader) ([]domain.Device, error) {
	if mock.DecodeOpRepDevlistFunc == nil {
		panic("ProtocolCodecMock.DecodeOpRepDevlistFunc: method is nil but ProtocolCodec.DecodeOpRepDevlist was just called")
	}
	callInfo := struct {
		R io.Reader
	}{
		R: r,
	}
	mock.lockDecodeOpRepDevlist.Lock()
	mock.calls.DecodeOpRepDevlist = append(mock.calls.DecodeOpRepDevlist, callInfo)
	mock.lockDecodeOpRepDevlist.Unlock()
	return mock.DecodeOpRepDevlistFunc(r)
}

// DecodeOpRepDevlistCalls gets all the calls that were made to DecodeOpRepDevlist.
// Check the length with:
//
//	len(mockedProtocolCodec.DecodeOpRepDevlistCalls())
func (mock *ProtocolCodecMock) DecodeOpRepDevlistCalls() []struct {
	R io.Reader
} {
	var calls []struct {
		R io.Reader
	}
	mock.lockDecodeOpRepDevlist.RLock()
	calls = mock.calls.DecodeOpRepDevlist
	mock.lockDecodeOpRepDevlist.RUnlock()
	return calls
}

// DecodeOpRepImport calls DecodeOpRepImportFunc.
func (mock *ProtocolCodecMock) DecodeOpRepImport(r io.Reader) (domain.Device, error) {
	if mock.DecodeOpRepImportFunc == nil {
		panic("ProtocolCodecMock.DecodeOpRepImportFunc: method is nil but ProtocolCodec.DecodeOpRepImport was just called")
	}
	callInfo := struct {
		R io.Reader
	}{
		R: r,
	}
	mock.lockDecodeOpRepImport.Lock()
	mock.calls.DecodeOpRepImport = append(mock.calls.DecodeOpRepImport, callInfo)
	mock.lockDecodeOpRepImport.Unlock()
	return mock.DecodeOpRepImportFunc(r)
}

// DecodeOpRepImportCalls gets all the calls that were made to DecodeOpRepImport.
// Check the length with:
//
//	len(mockedProtocolCodec.DecodeOpRepImportCalls())
func (mock *ProtocolCodecMock) DecodeOpRepImportCalls() []struct {
	R io.Reader
} {
	var calls []struct {
		R io.Reader
	}
	mock.lockDecodeOpRepImport.RLock()
	calls = mock.calls.DecodeOpRepImport
	mock.lockDecodeOpRepImport.RUnlock()
	return calls
}

// DecodeOpReqImport calls DecodeOpReqImportFunc.
func (mock *ProtocolCodecMock) DecodeOpReqImport(r io.Reader) (domain.BusID, error) {
	if mock.DecodeOpReqImportFunc == nil {
		panic("ProtocolCodecMock.DecodeOpReqImportFunc: method is nil but ProtocolCodec.DecodeOpReqImport was just called")
	}
	callInfo := struct {
		R io.Reader
	}{
		R: r,
	}
	mock.lockDecodeOpReqImport.Lock()
	mock.calls.DecodeOpReqImport = append(mock.calls.DecodeOpReqImport, callInfo)
	mock.lockDecodeOpReqImport.Unlock()
	return mock.DecodeOpReqImportFunc(r)
}

// DecodeOpReqImportCalls gets all the calls that were made to DecodeOpReqImport.
// Check the length with:
//
//	len(mockedProtocolCodec.DecodeOpReqImportCalls())
func (mock *ProtocolCodecMock) DecodeOpReqImportCalls() []struct {
	R io.Reader
} {
	var calls []struct {
		R io.Reader
	}
	mock.lockDecodeOpReqImport.RLock()
	calls = mock.calls.DecodeOpReqImport
	mock.lockDecodeOpReqImport.RUnlock()
	return calls
}

// EncodeOpRepDevlist calls EncodeOpRepDevlistFunc.
func (mock *ProtocolCodecMock) EncodeOpRepDevlist(w io.Writer, devs []domain.Device) error {
	if mock.EncodeOpRepDevlistFunc == nil {
		panic("ProtocolCodecMock.EncodeOpRepDevlistFunc: method is nil but ProtocolCodec.EncodeOpRepDevlist was just called")
	}
	callInfo := struct {
		W    io.Writer
		Devs []domain.Device
	}{
		W:    w,
		Devs: devs,
	}
	mock.lockEncodeOpRepDevlist.Lock()
	mock.calls.EncodeOpRepDevlist = append(mock.calls.EncodeOpRepDevlist, callInfo)
	mock.lockEncodeOpRepDevlist.Unlock()
	return mock.EncodeOpRepDevlistFunc(w, devs)
}

// EncodeOpRepDevlistCalls gets all the calls that were made to EncodeOpRepDevlist.
// Check the length with:
//
//	len(mockedProtocolCodec.EncodeOpRepDevlistCalls())
func (mock *ProtocolCodecMock) EncodeOpRepDevlistCalls() []struct {
	W    io.Writer
	Devs []domain.Device
} {
	var calls []struct {
		W    io.Writer
		Devs []domain.Device
	}
	mock.lockEncodeOpRepDevlist.RLock()
	calls = mock.calls.EncodeOpRepDevlist
	mock.lockEncodeOpRepDevlist.RUnlock()
	return calls
}

// EncodeOpRepImport calls EncodeOpRepImportFunc.
func (mock *ProtocolCodecMock) EncodeOpRepImport(w io.Writer, d domain.Device) error {
	if mock.EncodeOpRepImportFunc == nil {
		panic("ProtocolCodecMock.EncodeOpRepImportFunc: method is nil but ProtocolCodec.EncodeOpRepImport was just called")
	}
	callInfo := struct {
		W io.Writer
		D domain.Device
	}{
		W: w,
		D: d,
	}
	mock.lockEncodeOpRepImport.Lock()
	mock.calls.EncodeOpRepImport = append(mock.calls.EncodeOpRepImport, callInfo)
	mock.lockEncodeOpRepImport.Unlock()
	return mock.EncodeOpRepImportFunc(w, d)
}

// EncodeOpRepImportCalls gets all the calls that were made to EncodeOpRepImport.
// Check the length with:
//
//	len(mockedProtocolCodec.EncodeOpRepImportCalls())
func (mock *ProtocolCodecMock) EncodeOpRepImportCalls() []struct {
	W io.Writer
	D domain.Device
} {
	var calls []struct {
		W io.Writer
		D domain.Device
	}
	mock.lockEncodeOpRepImport.RLock()
	calls = mock.calls.EncodeOpRepImport
	mock.lockEncodeOpRepImport.RUnlock()
	return calls
}

// EncodeOpReqDevlist calls EncodeOpReqDevlistFunc.
func (mock *ProtocolCodecMock) EncodeOpReqDevlist() []byte {
	if mock.EncodeOpReqDevlistFunc == nil {
		panic("ProtocolCodecMock.EncodeOpReqDevlistFunc: method is nil but ProtocolCodec.EncodeOpReqDevlist was just called")
	}
	callInfo := struct {
	}{}
	mock.lockEncodeOpReqDevlist.Lock()
	mock.calls.EncodeOpReqDevlist = append(mock.calls.EncodeOpReqDevlist, callInfo)
	mock.lockEncodeOpReqDevlist.Unlock()
	return mock.EncodeOpReqDevlistFunc()
}

// EncodeOpReqDevlistCalls gets all the calls that were made to EncodeOpReqDevlist.
// Check the length with:
//
//	len(mockedProtocolCodec.EncodeOpReqDevlistCalls())
func (mock *ProtocolCodecMock) EncodeOpReqDevlistCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEncodeOpReqDevlist.RLock()
	calls = mock.calls.EncodeOpReqDevlist
	mock.lockEncodeOpReqDevlist.RUnlock()
	return calls
}

// EncodeOpReqImport calls EncodeOpReqImportFunc.
func (mock *ProtocolCodecMock) EncodeOpReqImport(w io.Writer, busID domain.BusID) error {
	if mock.EncodeOpReqImportFunc == nil {
		panic("ProtocolCodecMock.EncodeOpReqImportFunc: method is nil but ProtocolCodec.EncodeOpReqImport was just called")
	}
	callInfo := struct {
		W     io.Writer
		BusID domain.BusID
	}{
		W:     w,
		BusID: busID,
	}
	mock.lockEncodeOpReqImport.Lock()
	mock.calls.EncodeOpReqImport = append(mock.calls.EncodeOpReqImport, callInfo)
	mock.lockEncodeOpReqImport.Unlock()
	return mock.EncodeOpReqImportFunc(w, busID)
}

// EncodeOpReqImportCalls gets all the calls that were made to EncodeOpReqImport.
// Check the length with:
//
//	len(mockedProtocolCodec.EncodeOpReqImportCalls())
func (mock *ProtocolCodecMock) EncodeOpReqImportCalls() []struct {
	W     io.Writer
	BusID domain.BusID
} {
	var calls []struct {
		W     io.Writer
		BusID domain.BusID
	}
	mock.lockEncodeOpReqImport.RLock()
	calls = mock.calls.EncodeOpReqImport
	mock.lockEncodeOpReqImport.RUnlock()
	return calls
}
