// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app_test

import (
	"context"
	"sync"

	"github.com/abilisoft/usbip-go/internal/app"
	"github.com/abilisoft/usbip-go/pkg/domain"
)

// Ensure, that KernelEventsMock does implement app.KernelEvents.
// If this is not the case, regenerate this file with moq.
var _ app.KernelEvents = &KernelEventsMock{}

// KernelEventsMock is a mock implementation of app.KernelEvents.
//
//	func TestSomethingThatUsesKernelEvents(t *testing.T) {
//
//		// make and configure a mocked app.KernelEvents
//		mockedKernelEvents := &KernelEventsMock{
//			SubscribeFunc: func(ctx context.Context) (<-chan domain.Event, func(), error) {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedKernelEvents in code that requires app.KernelEvents
//		// and then make assertions.
//
//	}
type KernelEventsMock struct {
	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context) (<-chan domain.Event, func(), error)

	// calls tracks calls to the methods.
	calls struct {
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockSubscribe sync.RWMutex
}

// Subscribe calls SubscribeFunc.
func (mock *KernelEventsMock) Subscribe(ctx context.Context) (<-chan domain.Event, func(), error) {
	if mock.SubscribeFunc == nil {
		panic("KernelEventsMock.SubscribeFunc: method is nil but KernelEvents.Subscribe was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedKernelEvents.SubscribeCalls())
func (mock *KernelEventsMock) SubscribeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
