// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app_test

import (
	"context"
	"net"
	"sync"

	"github.com/abilisoft/usbip-go/internal/app"
	"github.com/abilisoft/usbip-go/pkg/domain"
)

// Ensure, that ImporterKernelMock does implement app.ImporterKernel.
// If this is not the case, regenerate this file with moq.
var _ app.ImporterKernel = &ImporterKernelMock{}

// ImporterKernelMock is a mock implementation of app.ImporterKernel.
//
//	func TestSomethingThatUsesImporterKernel(t *testing.T) {
//
//		// make and configure a mocked app.ImporterKernel
//		mockedImporterKernel := &ImporterKernelMock{
//			AttachRemoteFunc: func(ctx context.Context, conn net.Conn, spec app.RemoteDeviceSpec) (domain.PortID, error) {
//				panic("mock out the AttachRemote method")
//			},
//			DetachPortFunc: func(ctx context.Context, id domain.PortID) error {
//				panic("mock out the DetachPort method")
//			},
//			ListPortsFunc: func(ctx context.Context) ([]domain.Port, error) {
//				panic("mock out the ListPorts method")
//			},
//			ModulesAvailableFunc: func(ctx context.Context) error {
//				panic("mock out the ModulesAvailable method")
//			},
//		}
//
//		// use mockedImporterKernel in code that requires app.ImporterKernel
//		// and then make assertions.
//
//	}
type ImporterKernelMock struct {
	// AttachRemoteFunc mocks the AttachRemote method.
	AttachRemoteFunc func(ctx context.Context, conn net.Conn, spec app.RemoteDeviceSpec) (domain.PortID, error)

	// DetachPortFunc mocks the DetachPort method.
	DetachPortFunc func(ctx context.Context, id domain.PortID) error

	// ListPortsFunc mocks the ListPorts method.
	ListPortsFunc func(ctx context.Context) ([]domain.Port, error)

	// ModulesAvailableFunc mocks the ModulesAvailable method.
	ModulesAvailableFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// AttachRemote holds details about calls to the AttachRemote method.
		AttachRemote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Conn is the conn argument value.
			Conn net.Conn
			// Spec is the spec argument value.
			Spec app.RemoteDeviceSpec
		}
		// DetachPort holds details about calls to the DetachPort method.
		DetachPort []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID domain.PortID
		}
		// ListPorts holds details about calls to the ListPorts method.
		ListPorts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ModulesAvailable holds details about calls to the ModulesAvailable method.
		ModulesAvailable []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAttachRemote     sync.RWMutex
	lockDetachPort       sync.RWMutex
	lockListPorts        sync.RWMutex
	lockModulesAvailable sync.RWMutex
}

// AttachRemote calls AttachRemoteFunc.
func (mock *ImporterKernelMock) AttachRemote(ctx context.Context, conn net.Conn, spec app.RemoteDeviceSpec) (domain.PortID, error) {
	if mock.AttachRemoteFunc == nil {
		panic("ImporterKernelMock.AttachRemoteFunc: method is nil but ImporterKernel.AttachRemote was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Conn net.Conn
		Spec app.RemoteDeviceSpec
	}{
		Ctx:  ctx,
		Conn: conn,
		Spec: spec,
	}
	mock.lockAttachRemote.Lock()
	mock.calls.AttachRemote = append(mock.calls.AttachRemote, callInfo)
	mock.lockAttachRemote.Unlock()
	return mock.AttachRemoteFunc(ctx, conn, spec)
}

// AttachRemoteCalls gets all the calls that were made to AttachRemote.
// Check the length with:
//
//	len(mockedImporterKernel.AttachRemoteCalls())
func (mock *ImporterKernelMock) AttachRemoteCalls() []struct {
	Ctx  context.Context
	Conn net.Conn
	Spec app.RemoteDeviceSpec
} {
	var calls []struct {
		Ctx  context.Context
		Conn net.Conn
		Spec app.RemoteDeviceSpec
	}
	mock.lockAttachRemote.RLock()
	calls = mock.calls.AttachRemote
	mock.lockAttachRemote.RUnlock()
	return calls
}

// DetachPort calls DetachPortFunc.
func (mock *ImporterKernelMock) DetachPort(ctx context.Context, id domain.PortID) error {
	if mock.DetachPortFunc == nil {
		panic("ImporterKernelMock.DetachPortFunc: method is nil but ImporterKernel.DetachPort was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  domain.PortID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDetachPort.Lock()
	mock.calls.DetachPort = append(mock.calls.DetachPort, callInfo)
	mock.lockDetachPort.Unlock()
	return mock.DetachPortFunc(ctx, id)
}

// DetachPortCalls gets all the calls that were made to DetachPort.
// Check the length with:
//
//	len(mockedImporterKernel.DetachPortCalls())
func (mock *ImporterKernelMock) DetachPortCalls() []struct {
	Ctx context.Context
	ID  domain.PortID
} {
	var calls []struct {
		Ctx context.Context
		ID  domain.PortID
	}
	mock.lockDetachPort.RLock()
	calls = mock.calls.DetachPort
	mock.lockDetachPort.RUnlock()
	return calls
}

// ListPorts calls ListPortsFunc.
func (mock *ImporterKernelMock) ListPorts(ctx context.Context) ([]domain.Port, error) {
	if mock.ListPortsFunc == nil {
		panic("ImporterKernelMock.ListPortsFunc: method is nil but ImporterKernel.ListPorts was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListPorts.Lock()
	mock.calls.ListPorts = append(mock.calls.ListPorts, callInfo)
	mock.lockListPorts.Unlock()
	return mock.ListPortsFunc(ctx)
}

// ListPortsCalls gets all the calls that were made to ListPorts.
// Check the length with:
//
//	len(mockedImporterKernel.ListPortsCalls())
func (mock *ImporterKernelMock) ListPortsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListPorts.RLock()
	calls = mock.calls.ListPorts
	mock.lockListPorts.RUnlock()
	return calls
}

// ModulesAvailable calls ModulesAvailableFunc.
func (mock *ImporterKernelMock) ModulesAvailable(ctx context.Context) error {
	if mock.ModulesAvailableFunc == nil {
		panic("ImporterKernelMock.ModulesAvailableFunc: method is nil but ImporterKernel.ModulesAvailable was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockModulesAvailable.Lock()
	mock.calls.ModulesAvailable = append(mock.calls.ModulesAvailable, callInfo)
	mock.lockModulesAvailable.Unlock()
	return mock.ModulesAvailableFunc(ctx)
}

// ModulesAvailableCalls gets all the calls that were made to ModulesAvailable.
// Check the length with:
//
//	len(mockedImporterKernel.ModulesAvailableCalls())
func (mock *ImporterKernelMock) ModulesAvailableCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockModulesAvailable.RLock()
	calls = mock.calls.ModulesAvailable
	mock.lockModulesAvailable.RUnlock()
	return calls
}
