// SPDX-FileCopyrightText: 2026 AbiliSoft
// SPDX-License-Identifier: Apache-2.0

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app_test

import (
	"context"
	"github.com/abilisoft/usbip-go/internal/app"
	"github.com/abilisoft/usbip-go/pkg/domain"
	"net"
	"sync"
)

// Ensure, that ExporterKernelMock does implement app.ExporterKernel.
// If this is not the case, regenerate this file with moq.
var _ app.ExporterKernel = &ExporterKernelMock{}

// ExporterKernelMock is a mock implementation of app.ExporterKernel.
//
//	func TestSomethingThatUsesExporterKernel(t *testing.T) {
//
//		// make and configure a mocked app.ExporterKernel
//		mockedExporterKernel := &ExporterKernelMock{
//			BindFunc: func(ctx context.Context, busID domain.BusID) error {
//				panic("mock out the Bind method")
//			},
//			DisconnectFunc: func(ctx context.Context, busID domain.BusID) error {
//				panic("mock out the Disconnect method")
//			},
//			ExportOnConnFunc: func(ctx context.Context, conn net.Conn, busID domain.BusID) error {
//				panic("mock out the ExportOnConn method")
//			},
//			ListLocalDevicesFunc: func(ctx context.Context) ([]domain.Device, error) {
//				panic("mock out the ListLocalDevices method")
//			},
//			ModulesAvailableFunc: func(ctx context.Context) error {
//				panic("mock out the ModulesAvailable method")
//			},
//			UnbindFunc: func(ctx context.Context, busID domain.BusID) error {
//				panic("mock out the Unbind method")
//			},
//		}
//
//		// use mockedExporterKernel in code that requires app.ExporterKernel
//		// and then make assertions.
//
//	}
type ExporterKernelMock struct {
	// BindFunc mocks the Bind method.
	BindFunc func(ctx context.Context, busID domain.BusID) error

	// DisconnectFunc mocks the Disconnect method.
	DisconnectFunc func(ctx context.Context, busID domain.BusID) error

	// ExportOnConnFunc mocks the ExportOnConn method.
	ExportOnConnFunc func(ctx context.Context, conn net.Conn, busID domain.BusID) error

	// ListLocalDevicesFunc mocks the ListLocalDevices method.
	ListLocalDevicesFunc func(ctx context.Context) ([]domain.Device, error)

	// ModulesAvailableFunc mocks the ModulesAvailable method.
	ModulesAvailableFunc func(ctx context.Context) error

	// UnbindFunc mocks the Unbind method.
	UnbindFunc func(ctx context.Context, busID domain.BusID) error

	// calls tracks calls to the methods.
	calls struct {
		// Bind holds details about calls to the Bind method.
		Bind []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BusID is the busID argument value.
			BusID domain.BusID
		}
		// Disconnect holds details about calls to the Disconnect method.
		Disconnect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BusID is the busID argument value.
			BusID domain.BusID
		}
		// ExportOnConn holds details about calls to the ExportOnConn method.
		ExportOnConn []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Conn is the conn argument value.
			Conn net.Conn
			// BusID is the busID argument value.
			BusID domain.BusID
		}
		// ListLocalDevices holds details about calls to the ListLocalDevices method.
		ListLocalDevices []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ModulesAvailable holds details about calls to the ModulesAvailable method.
		ModulesAvailable []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Unbind holds details about calls to the Unbind method.
		Unbind []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BusID is the busID argument value.
			BusID domain.BusID
		}
	}
	lockBind             sync.RWMutex
	lockDisconnect       sync.RWMutex
	lockExportOnConn     sync.RWMutex
	lockListLocalDevices sync.RWMutex
	lockModulesAvailable sync.RWMutex
	lockUnbind           sync.RWMutex
}

// Bind calls BindFunc.
func (mock *ExporterKernelMock) Bind(ctx context.Context, busID domain.BusID) error {
	if mock.BindFunc == nil {
		panic("ExporterKernelMock.BindFunc: method is nil but ExporterKernel.Bind was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		BusID domain.BusID
	}{
		Ctx:   ctx,
		BusID: busID,
	}
	mock.lockBind.Lock()
	mock.calls.Bind = append(mock.calls.Bind, callInfo)
	mock.lockBind.Unlock()
	return mock.BindFunc(ctx, busID)
}

// BindCalls gets all the calls that were made to Bind.
// Check the length with:
//
//	len(mockedExporterKernel.BindCalls())
func (mock *ExporterKernelMock) BindCalls() []struct {
	Ctx   context.Context
	BusID domain.BusID
} {
	var calls []struct {
		Ctx   context.Context
		BusID domain.BusID
	}
	mock.lockBind.RLock()
	calls = mock.calls.Bind
	mock.lockBind.RUnlock()
	return calls
}

// Disconnect calls DisconnectFunc.
func (mock *ExporterKernelMock) Disconnect(ctx context.Context, busID domain.BusID) error {
	if mock.DisconnectFunc == nil {
		panic("ExporterKernelMock.DisconnectFunc: method is nil but ExporterKernel.Disconnect was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		BusID domain.BusID
	}{
		Ctx:   ctx,
		BusID: busID,
	}
	mock.lockDisconnect.Lock()
	mock.calls.Disconnect = append(mock.calls.Disconnect, callInfo)
	mock.lockDisconnect.Unlock()
	return mock.DisconnectFunc(ctx, busID)
}

// DisconnectCalls gets all the calls that were made to Disconnect.
// Check the length with:
//
//	len(mockedExporterKernel.DisconnectCalls())
func (mock *ExporterKernelMock) DisconnectCalls() []struct {
	Ctx   context.Context
	BusID domain.BusID
} {
	var calls []struct {
		Ctx   context.Context
		BusID domain.BusID
	}
	mock.lockDisconnect.RLock()
	calls = mock.calls.Disconnect
	mock.lockDisconnect.RUnlock()
	return calls
}

// ExportOnConn calls ExportOnConnFunc.
func (mock *ExporterKernelMock) ExportOnConn(ctx context.Context, conn net.Conn, busID domain.BusID) error {
	if mock.ExportOnConnFunc == nil {
		panic("ExporterKernelMock.ExportOnConnFunc: method is nil but ExporterKernel.ExportOnConn was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Conn  net.Conn
		BusID domain.BusID
	}{
		Ctx:   ctx,
		Conn:  conn,
		BusID: busID,
	}
	mock.lockExportOnConn.Lock()
	mock.calls.ExportOnConn = append(mock.calls.ExportOnConn, callInfo)
	mock.lockExportOnConn.Unlock()
	return mock.ExportOnConnFunc(ctx, conn, busID)
}

// ExportOnConnCalls gets all the calls that were made to ExportOnConn.
// Check the length with:
//
//	len(mockedExporterKernel.ExportOnConnCalls())
func (mock *ExporterKernelMock) ExportOnConnCalls() []struct {
	Ctx   context.Context
	Conn  net.Conn
	BusID domain.BusID
} {
	var calls []struct {
		Ctx   context.Context
		Conn  net.Conn
		BusID domain.BusID
	}
	mock.lockExportOnConn.RLock()
	calls = mock.calls.ExportOnConn
	mock.lockExportOnConn.RUnlock()
	return calls
}

// ListLocalDevices calls ListLocalDevicesFunc.
func (mock *ExporterKernelMock) ListLocalDevices(ctx context.Context) ([]domain.Device, error) {
	if mock.ListLocalDevicesFunc == nil {
		panic("ExporterKernelMock.ListLocalDevicesFunc: method is nil but ExporterKernel.ListLocalDevices was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListLocalDevices.Lock()
	mock.calls.ListLocalDevices = append(mock.calls.ListLocalDevices, callInfo)
	mock.lockListLocalDevices.Unlock()
	return mock.ListLocalDevicesFunc(ctx)
}

// ListLocalDevicesCalls gets all the calls that were made to ListLocalDevices.
// Check the length with:
//
//	len(mockedExporterKernel.ListLocalDevicesCalls())
func (mock *ExporterKernelMock) ListLocalDevicesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListLocalDevices.RLock()
	calls = mock.calls.ListLocalDevices
	mock.lockListLocalDevices.RUnlock()
	return calls
}

// ModulesAvailable calls ModulesAvailableFunc.
func (mock *ExporterKernelMock) ModulesAvailable(ctx context.Context) error {
	if mock.ModulesAvailableFunc == nil {
		panic("ExporterKernelMock.ModulesAvailableFunc: method is nil but ExporterKernel.ModulesAvailable was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockModulesAvailable.Lock()
	mock.calls.ModulesAvailable = append(mock.calls.ModulesAvailable, callInfo)
	mock.lockModulesAvailable.Unlock()
	return mock.ModulesAvailableFunc(ctx)
}

// ModulesAvailableCalls gets all the calls that were made to ModulesAvailable.
// Check the length with:
//
//	len(mockedExporterKernel.ModulesAvailableCalls())
func (mock *ExporterKernelMock) ModulesAvailableCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockModulesAvailable.RLock()
	calls = mock.calls.ModulesAvailable
	mock.lockModulesAvailable.RUnlock()
	return calls
}

// Unbind calls UnbindFunc.
func (mock *ExporterKernelMock) Unbind(ctx context.Context, busID domain.BusID) error {
	if mock.UnbindFunc == nil {
		panic("ExporterKernelMock.UnbindFunc: method is nil but ExporterKernel.Unbind was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		BusID domain.BusID
	}{
		Ctx:   ctx,
		BusID: busID,
	}
	mock.lockUnbind.Lock()
	mock.calls.Unbind = append(mock.calls.Unbind, callInfo)
	mock.lockUnbind.Unlock()
	return mock.UnbindFunc(ctx, busID)
}

// UnbindCalls gets all the calls that were made to Unbind.
// Check the length with:
//
//	len(mockedExporterKernel.UnbindCalls())
func (mock *ExporterKernelMock) UnbindCalls() []struct {
	Ctx   context.Context
	BusID domain.BusID
} {
	var calls []struct {
		Ctx   context.Context
		BusID domain.BusID
	}
	mock.lockUnbind.RLock()
	calls = mock.calls.Unbind
	mock.lockUnbind.RUnlock()
	return calls
}
