// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app_test

import (
	"context"
	"net"
	"sync"

	"github.com/abilisoft/usbip-go/internal/app"
	"github.com/abilisoft/usbip-go/pkg/domain"
)

// Ensure, that TransportMock does implement app.Transport.
// If this is not the case, regenerate this file with moq.
var _ app.Transport = &TransportMock{}

// TransportMock is a mock implementation of app.Transport.
//
//	func TestSomethingThatUsesTransport(t *testing.T) {
//
//		// make and configure a mocked app.Transport
//		mockedTransport := &TransportMock{
//			DialFunc: func(ctx context.Context, endpoint domain.RemoteEndpoint, opts app.TransportOptions) (net.Conn, error) {
//				panic("mock out the Dial method")
//			},
//			ListenFunc: func(ctx context.Context, addr string, opts app.TransportOptions) (net.Listener, error) {
//				panic("mock out the Listen method")
//			},
//		}
//
//		// use mockedTransport in code that requires app.Transport
//		// and then make assertions.
//
//	}
type TransportMock struct {
	// DialFunc mocks the Dial method.
	DialFunc func(ctx context.Context, endpoint domain.RemoteEndpoint, opts app.TransportOptions) (net.Conn, error)

	// ListenFunc mocks the Listen method.
	ListenFunc func(ctx context.Context, addr string, opts app.TransportOptions) (net.Listener, error)

	// calls tracks calls to the methods.
	calls struct {
		// Dial holds details about calls to the Dial method.
		Dial []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Endpoint is the endpoint argument value.
			Endpoint domain.RemoteEndpoint
			// Opts is the opts argument value.
			Opts app.TransportOptions
		}
		// Listen holds details about calls to the Listen method.
		Listen []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Addr is the addr argument value.
			Addr string
			// Opts is the opts argument value.
			Opts app.TransportOptions
		}
	}
	lockDial   sync.RWMutex
	lockListen sync.RWMutex
}

// Dial calls DialFunc.
func (mock *TransportMock) Dial(ctx context.Context, endpoint domain.RemoteEndpoint, opts app.TransportOptions) (net.Conn, error) {
	if mock.DialFunc == nil {
		panic("TransportMock.DialFunc: method is nil but Transport.Dial was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Endpoint domain.RemoteEndpoint
		Opts     app.TransportOptions
	}{
		Ctx:      ctx,
		Endpoint: endpoint,
		Opts:     opts,
	}
	mock.lockDial.Lock()
	mock.calls.Dial = append(mock.calls.Dial, callInfo)
	mock.lockDial.Unlock()
	return mock.DialFunc(ctx, endpoint, opts)
}

// DialCalls gets all the calls that were made to Dial.
// Check the length with:
//
//	len(mockedTransport.DialCalls())
func (mock *TransportMock) DialCalls() []struct {
	Ctx      context.Context
	Endpoint domain.RemoteEndpoint
	Opts     app.TransportOptions
} {
	var calls []struct {
		Ctx      context.Context
		Endpoint domain.RemoteEndpoint
		Opts     app.TransportOptions
	}
	mock.lockDial.RLock()
	calls = mock.calls.Dial
	mock.lockDial.RUnlock()
	return calls
}

// Listen calls ListenFunc.
func (mock *TransportMock) Listen(ctx context.Context, addr string, opts app.TransportOptions) (net.Listener, error) {
	if mock.ListenFunc == nil {
		panic("TransportMock.ListenFunc: method is nil but Transport.Listen was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Addr string
		Opts app.TransportOptions
	}{
		Ctx:  ctx,
		Addr: addr,
		Opts: opts,
	}
	mock.lockListen.Lock()
	mock.calls.Listen = append(mock.calls.Listen, callInfo)
	mock.lockListen.Unlock()
	return mock.ListenFunc(ctx, addr, opts)
}

// ListenCalls gets all the calls that were made to Listen.
// Check the length with:
//
//	len(mockedTransport.ListenCalls())
func (mock *TransportMock) ListenCalls() []struct {
	Ctx  context.Context
	Addr string
	Opts app.TransportOptions
} {
	var calls []struct {
		Ctx  context.Context
		Addr string
		Opts app.TransportOptions
	}
	mock.lockListen.RLock()
	calls = mock.calls.Listen
	mock.lockListen.RUnlock()
	return calls
}
