load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "client_lib",
    srcs = ["main.go"],
    importpath = "github.com/abilisoft/usbip-go/examples/client",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/domain",
        "//pkg/usbip",
    ],
)

go_binary(
    name = "client",
    embed = [":client_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "client_test",
    size = "small",
    srcs = ["main_test.go"],
    embed = [":client_lib"],
    deps = ["@com_github_stretchr_testify//require"],
)

filegroup(
    name = "go_srcs",
    srcs = glob(["*.go"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "testdata_files",
    srcs = glob(
        ["testdata/**"],
        allow_empty = True,
    ),
    visibility = ["//visibility:public"],
)
