load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "protocol",
    srcs = [
        "doc.go",
        "opcodes.go",
    ],
    importpath = "github.com/abilisoft/usbip-go/internal/protocol",
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "go_srcs",
    srcs = glob(["*.go"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "repo_bazel_files",
    srcs = ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "testdata_files",
    srcs = glob(
        ["testdata/**"],
        allow_empty = True,
    ),
    visibility = ["//visibility:public"],
)
