# SPDX-FileCopyrightText: 2026 AbiliSoft
# SPDX-License-Identifier: Apache-2.0
#
name: Integration (microVM)
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  integration:
    name: Integration (hermetic microVM)
    runs-on: [self-hosted, linux, kvm]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
      - name: Build microVM closure
        run: nix develop --command task ci:vm:build
      - name: Integration tests inside microVM
        run: nix develop --command task ci:vm:test:integration
