# SPDX-FileCopyrightText: 2026 AbiliSoft
# SPDX-License-Identifier: Apache-2.0
#
name: Integration (microVM)
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  integration:
    name: Integration (hermetic microVM)
    runs-on: [self-hosted, linux, kvm]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@ab6bcb2d5af0e904d04aea750e2089e9dc4cbfdd # v13
      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
      - name: Build microVM closure
        run: nix develop --command task ci:vm:build
      - name: Integration tests inside microVM
        run: nix develop --command task ci:vm:test:integration
